### ISSUE TITLE
test error:  dropbox file not found

### ISSUE THREAD

**Issue by cometsong** [mlangill/MicrobeDB#7]
I've just downloaded and am trying to use the software, however i'm getting errors in the initial testing phase.

Log of attempt:
`2016/01/26 14:21:13> Downloading file: Bacteria_2016-01-26/NCBI_orginfo.txt from Dropbox at: http://dl.dropbox.com/u/5329340/NCBI_orginfo.txt`
`2016/01/26 14:21:14> Problem with downloading! Waiting 60 seconds before attempting again.`
`2016/01/26 14:21:22> Error with downloading the new version: No such file or directory`

I checked the url: `http://dl.dropbox.com/u/5329340/NCBI_orginfo.txt` and it gave a delightful 404 error.

scripts/download_version.pl: line 327:
`#Note4: As of Nov. 15,2012 the metadata files are not available from NCBI ftp site. As temporary solution I have obtained the most recent metadata as of June 2012 and I am hosting these files via Dropbox. Therefore, metadata will only exist for genomes deposited before this date.`

Is there something this can be replaced with?  It clearly is not for recent genomes, as only the ones before 06/2012 are available.

In `Note3` the file `ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt` is mentioned as still using older genome ids, not the latest BioProject ids.  Is this still the case?

Thanks for your help!
-Benjamin-

**Comment by lairdm** [comment]
Hi Benjamin,

Due to changes in how NCBI organized it's ftp site, MicrobeDB wasn't able to function anymore in the manner intended. Instead of trying to fix up the old code, I decided to rewrite it with Morgan's blessing.

To achieve the same local mirroring functionality, I recommend you take a look at MicrobeDB v2, located over here:
https://github.com/lairdm/microbedb

Let us know if you have any issues or questions (Morgan I hope you don't mind me jumping in on this :) )

**Comment by cometsong** [comment]
**Delightful!**
Thanks @lairdm!
I'll check out this version immediately.
